version: 2

models:
  - name: cs_tickets_self_serve_mart
    description: >
      Self-serve customer support mart providing a 360-degree view of support
      tickets enriched with rental, vehicle, payment, and user experience
      attributes. Designed for deep-dive analysis, debugging, and ad-hoc
      investigations by CS and operations teams.

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - ticket_id

      - dbt_utils.expression_is_true:
          expression: "ticket_created_at <= CURRENT_TIMESTAMP()"

      - dbt_utils.expression_is_true:
          expression: "ticket_updated_at >= ticket_created_at"

      - dbt_utils.expression_is_true:
          expression: "rental_duration_min IS NULL OR rental_duration_min >= 0"

      - dbt_utils.expression_is_true:
          expression: "gross_revenue IS NULL OR gross_revenue >= 0"

      - dbt_utils.expression_is_true:
          expression: "net_revenue IS NULL OR net_revenue <= gross_revenue"

    columns:
      # -----------------------
      # Ticket core attributes
      # -----------------------
      - name: ticket_id
        description: Unique identifier of the support ticket.
        tests:
          - not_null

      - name: rental_id
        description: Identifier of the rental linked to the support ticket, if any.

      - name: user_id
        description: Identifier of the user who created the support ticket.

      - name: is_linked_to_rental
        description: Indicates whether the support ticket is linked to a rental.

      - name: category
        description: "{{ doc('support_ticket_category') }}"

      - name: subject
        description: Subject or issue type of the support ticket.

      - name: description
        description: Detailed description provided in the support ticket.

      - name: priority
        description: "{{ doc('support_ticket_priority') }}"
      
      - name: status
        description: "{{ doc('support_ticket_status') }}"

      - name: channel
        description: "{{ doc('support_ticket_channel') }}"

      - name: ticket_support_rating
        description: Customer satisfaction rating associated with the support ticket.

      - name: reopen_count
        description: Number of times the support ticket was reopened.

      - name: escalation_count
        description: Number of times the support ticket was escalated.

      - name: first_response_at
        description: Timestamp of the first response to the support ticket.

      - name: first_escalated_at
        description: Timestamp of the first escalation event for the support ticket.

      - name: resolved_at
        description: Timestamp when the support ticket was resolved.

      - name: first_response_time_minutes
        description: Time in minutes between ticket creation and first response.

      - name: first_response_time_hours
        description: Time in hours between ticket creation and first response.

      - name: resolution_time_minutes
        description: Time in minutes between ticket creation and resolution.

      - name: resolution_time_hours
        description: Time in hours between ticket creation and resolution.

      - name: resolved_within_24hrs
        description: Indicates whether the ticket was resolved within 24 hours.

      - name: ticket_created_at
        description: Timestamp when the support ticket was created.

      - name: ticket_updated_at
        description: Timestamp when the support ticket was last updated.

      # -----------------------
      # Rental & vehicle IDs
      # -----------------------
      - name: vehicle_id
        description: Identifier of the vehicle associated with the rental.

      - name: model_id
        description: Identifier of the vehicle model.

      - name: fleet_id
        description: Identifier of the fleet to which the vehicle belongs.

      - name: package_id
        description: Identifier of the rental package.

      - name: start_city_id
        description: City identifier where the rental started.

      - name: end_city_id
        description: City identifier where the rental ended.

      - name: reservation_id
        description: Identifier of the reservation linked to the rental.

      - name: incident_id
        description: Identifier of the incident linked to the rental, if any.

      - name: promo_id
        description: Identifier of the promotion applied to the rental, if any.

      # -----------------------
      # Rental attributes
      # -----------------------
      - name: start_time
        description: Timestamp when the rental started.

      - name: end_time
        description: Timestamp when the rental ended.

      - name: start_city
        description: Name of the city where the rental started.

      - name: end_city
        description: Name of the city where the rental ended.

      - name: is_inter_city_travel
        description: Indicates whether the rental involved inter-city travel.

      - name: rental_status
        description: "{{ doc('rental_status') }}"

      - name: package_name
        description: "{{ doc('rental_package') }}"

      - name: model_name
        description: Vehicle model name.

      - name: brand
        description: Vehicle brand.

      - name: energy_type
        description: Energy type of the vehicle.

      - name: vehicle_segment
        description: "{{ doc('vehicle_model_segment') }}"

      - name: vehicle_seats
        description: Number of seats in the vehicle.

      - name: fleet_name
        description: Name of the fleet to which the vehicle belongs.

      - name: company_type
        description: "{{ doc('vehicle_fleet_company_type') }}"

      # -----------------------
      # Usage & financials
      # -----------------------
      - name: rental_duration_min
        description: Rental duration in minutes.

      - name: rental_duration_hour
        description: Rental duration in hours.

      - name: distance_km
        description: Distance traveled during the rental in kilometers.

      - name: rental_cost
        description: Base cost of the rental.

      - name: paid_amount
        description: Total amount successfully paid for the rental.

      - name: refunded_amount
        description: Total refunded amount for the rental.

      - name: failed_amount
        description: Total failed payment amount for the rental.

      - name: wallet_paid_amount
        description: Portion of payment made via wallet.

      - name: card_paid_amount
        description: Portion of payment made via card.

      - name: discount_amount
        description: Discount amount applied to the rental.

      - name: gross_revenue
        description: Gross revenue generated by the rental.

      - name: net_revenue
        description: Net revenue after discounts and refunds.

      - name: has_refund
        description: Indicates whether the rental has any refund.

      - name: used_promotion
        description: Indicates whether a promotion was used.

      # -----------------------
      # Ratings
      # -----------------------
      - name: avg_rating_value
        description: Average rating value received for the rental.

      - name: rating_count
        description: Number of ratings received for the rental.

      - name: is_5_star_rating
        description: Indicates whether the rental received a 5-star rating.

      - name: is_1_star_rating
        description: Indicates whether the rental received a 1-star rating.


  - name: cs_daily_kpis_mart
    description: >
      Customer support daily KPI mart for the car-sharing business. Aggregated
      at date, ticket attributes, and linkage level, this mart supports both
      created-date and closed-date analyses to monitor ticket volume, resolution
      performance, escalations, response times, and customer satisfaction.
      Designed for flexible BI reporting via date-type switching.

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - date_type
            - date
            - is_linked_to_rental
            - category
            - subject
            - priority
            - channel

      - dbt_utils.expression_is_true:
          expression: "total_tickets >= 0"

      - dbt_utils.expression_is_true:
          expression: "resolved_tickets >= 0"

      - dbt_utils.expression_is_true:
          expression: "open_tickets >= 0"

      - dbt_utils.expression_is_true:
          expression: "resolved_tickets <= total_tickets"

      - dbt_utils.expression_is_true:
          expression: "open_tickets <= total_tickets"

      - dbt_utils.expression_is_true:
          expression: "date <= CURRENT_DATE()"

    columns:
      - name: date_type
        description: Indicates whether KPIs are aggregated by ticket creation date or resolution date.
        tests:
          - not_null
          - accepted_values:
              values: ['created', 'closed']

      - name: date
        description: Calendar date used for aggregating ticket KPIs.
        tests:
          - not_null

      - name: is_linked_to_rental
        description: Indicates whether the support tickets are linked to rentals.

      - name: category
        description: "{{ doc('support_ticket_category') }}"

      - name: subject
        description: Subject or issue type of the support tickets.

      - name: priority
        description: "{{ doc('support_ticket_priority') }}"

      - name: channel
        description: "{{ doc('support_ticket_channel') }}"

      - name: total_tickets
        description: Total number of support tickets for the given date and dimensions.

      - name: resolved_tickets
        description: Number of support tickets resolved for the given date and dimensions.

      - name: open_tickets
        description: Number of support tickets not resolved for the given date and dimensions.

      - name: reopen_count
        description: Total number of times tickets were reopened.

      - name: escalation_count
        description: Total number of times tickets were escalated.

      - name: avg_first_response_time_hours
        description: Average time in hours from ticket creation to first response.

      - name: avg_resolution_time_hours
        description: Average time in hours from ticket creation to resolution.

      - name: tickets_resolved_within_24hrs
        description: Number of tickets resolved within 24 hours of creation.

      - name: avg_ticket_support_rating
        description: Average customer satisfaction rating for support tickets.

      - name: total_rentals
        description: Total number of rentals on the corresponding date, used to compute contact rates in BI tools.
