version: 2

sources:
  - name: drive_raw
    description: "Raw tables containing JSON data ingested from the DriveX database on MongoDB"
    tags: ['drive', 'raw']

    #  Freshness test at source level (default for all source tables)
    # freshness:
    #   warn_after: {count: 24, period: hour}
    #   error_after: {count: 48, period: hour}
    # loaded_at_field: _etl_loaded_at

    # source tables
    tables:
      - name: drive_city_raw
      - name: drive_country_raw
      - name: drive_market_raw
      - name: drive_user_raw
      - name: drive_vehicle_model_raw
      - name: drive_vehicle_fleet_raw
      - name: drive_vehicle_raw
      - name: drive_trip_package_raw
      - name: drive_promotion_raw
      - name: drive_user_promotion_raw
      - name: drive_reservation_raw
      - name: drive_rental_raw
      - name: drive_rental_rating_raw
      - name: drive_payment_raw
      - name: drive_refund_raw
      - name: drive_incident_raw
      - name: drive_support_ticket_raw
      - name: drive_ticket_history_raw
